### ISSUE TITLE
Overlay on top of other windows

### ISSUE THREAD

**Issue by nomis51** [nomis51/Menagerie#25]
The overlay goes on top of other windows, even if the game is not focused.

**Comment by nomis51** [comment]
![image](https://user-images.githubusercontent.com/25111613/126051238-78c0e7e8-1c13-4ae6-b7b2-a0291c09662c.png)

**Comment by nomis51** [comment]
Will be fixed in next release.

**Comment by nomis51** [comment]
Fixed in 1.4.3

**Comment by zzeneg** [comment]
hey @nomis51, I still have this issue in 2.1.2 (and #26 because of it). Win 11, game in Windowed Fullscreen mode.
![image](https://user-images.githubusercontent.com/910255/186607441-44ba90ec-6ff8-4096-8886-8d210f07e0fd.png)

**Comment by nomis51** [comment]
> hey @nomis51, I still have this issue in 2.1.2 (and #26 because of it). Win 11, game in Windowed Fullscreen mode. ![image](https://user-images.githubusercontent.com/910255/186607441-44ba90ec-6ff8-4096-8886-8d210f07e0fd.png)

As of 2.0 and upwards, this is the expected behavior (at least for now). The app won't hide itself when you alt+tab for two reasons : 

- I wasn't satisfied with the performance of it when releasing 2.0, which a complete rewrite (no code from 1.0 in here, so it's not related the this issue/bug in particular)
- It was designed to take into account multiple monitors. Previously in version 1.0, if you were working on a separate monitor, like browsing the trade website, the overlay would've hide itself, which is not what I wanted. 

The goal was to make it hide itself when you're not in-game on the primary monitor, but not on other monitors, so you can still see the offers and other overlay stuff. But, like I said it wasn't working well enough for the league start with 2.0 release, so it has been omitted for now.

You can still hide manually the overlay by hitting `F3` in-game, which will prevent the overlap with the taskbar

![image](https://user-images.githubusercontent.com/25111613/186663957-4a98b35f-79e6-4fa1-b178-b14cf9113dc7.png)

Which is caused by the game being in fullscreen (the borderless version) and overlay being "attached" to it, so it tries to put itself on top of everything, so Windows kind of say "excuse me, please go ahead, i'll hide myself".

**Comment by nomis51** [comment]
@zzeneg I'll be deploying today an update adding an auto-hide to the overlay (until I found an acceptable solution for the reasons stated above), since it seems to be an issue for you.

Feel free to submit issues here or on discord about anything and I'll take a look at it.

Thanks for the report!

**Comment by zzeneg** [comment]
It is an issue as I alt-tab quite a lot and keep PoE running in the background. It's the only thing that does not allow me to enjoy Menagerie :) Thanks a lot, looking forward to test it!
