### ISSUE TITLE
Windows taskbar goes under the game when the overlay is running (on main screen)

### ISSUE THREAD

**Issue by nomis51** [nomis51/Menagerie#26]
![image](https://user-images.githubusercontent.com/25111613/126051325-7bc0e42c-6386-4ac0-9b8f-edc788d3349b.png)

**Comment by nomis51** [comment]
Will be fixed in next release.

**Comment by nomis51** [comment]
Fixed in 1.4.3.

Because of #25 , the game was still trying to go fullscreen, hiding the taskbar, because the overlay was bringing it on top.

**Comment by zzeneg** [comment]
hey @nomis51, I still have this issue in 2.1.2 (and #25 because of it). Win 11, game in Windowed Fullscreen mode.
